### ISSUE TITLE
Unknown charset error

### ISSUE THREAD

**Issue by rockenbach** [lucasdiedrich/ojs#10]
Lucas, congratulations for the work you have done!

I'm trying to run ojs for the first time and found this docker repository. I getting the following error and would be very grateful if you can help me because I'm trying to get this software running locally for all day long.

> Errors occurred during installation
A database error has occurred: Server sent charset unknown to the client. Please, report to the developers

First I kept only `- /etc/localtime:/etc/localtime` volume of pkp-ojs service, and it was my only modification. Second, I create the file `config/ojs.config.inc.php` based on the [default template](https://github.com/pkp/ojs/blob/master/config.TEMPLATE.inc.php) and changed only these configs bellow:

```
client_charset = utf-8
connection_charset = uft8
database_charset = uft8
```

but the same error still happening.

On the installation page I choose 'Unicode (UTF-8)' on all charset configs and on the database section I defined:

```
Drive: MySQL
Host: mysql-ojs (the mysql' container name)
Username: ojs
Password: ojs
Database name: ojs
Unchecked 'create new database' (before I checked the mysql container and the database exists as expected)
```

Do you have some clue on what is the problema and how can I fix that?

**Comment by lucasdiedrich** [comment]
Hi @rockenbach, can you please insert your docker-compose file or the exactly docker run CMD which you are using?

This is odd, the default charset is UTF-8, this shouldn't be happening.

**Comment by rockenbach** [comment]
Hi, @lucasdiedrich. Thanks for your time.

My current docker-compose is:

```
version: "3.3"

services:

    mysql-ojs:
        image: mysql:latest
        container_name: mysql-ojs
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ojs
            MYSQL_DATABASE: ojs
            MYSQL_USER: ojs
            MYSQL_PASSWORD: ojs

    pkp-ojs:
        image: lucasdiedrich/ojs:latest
        #build:
        #    context: .
        container_name: pkp-ojs
        restart: always
        ports:
            - "8080:80"
            - "8443:443"
        # volumes:
            # - /etc/localtime:/etc/localtime             # to sync the container clock with localhost.
            # - ./files/private:/var/www/files            # ojs' private files
            # - ./files/public:/var/www/html/public       # ojs' public files
            # - ./files/logs:/var/log/apache2             # apache logs
            
            # default
            #- ./config/ojs.config.inc.php:/var/www/html/config.inc.php      # ojs' config
            # - ./config/apache.htaccess:/var/www/html/.htaccess              # ojs' htaccess
            #- ./config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini  # php config
        environment:
            OJS_CLI_INSTALL: 1
            OJS_DB_HOST: 'mysql-ojs'
        depends_on: 
            - mysql-ojs
```
I also checked the `character_set_database` and `collation_database` of ojs database and the first was `utf8mb4` and the last was `utf8mb4_0900_ai_ci`.

At least for my knowledge the default configs should work fine, but I'm not an expert. Do you have some ideia on how to solve this problem?

Looks like this isn't a bug related to your project, so if you wanna to close this issue I'm okay with it and I'll come back to make a comment if I find the answer.
